
name: inventa
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - python
  - numpy
  - pip
  - pandas
  - rdkit::rdkit
  - molvs
  - pip:
    - ipykernel
    - jupyter_client
    - scikit_bio
    - scikit_learn
    - matplotlib
    - plotly
    - ipywidgets
    - cimcb_lite
    - lineup_widget
    - jupyter_contrib_nbextensions
    - umap-learn
    - memo-ms
